#include "stdafx.h"

#include "SearchAThing.Solid.Wrapper.h"

#include "gp_pnt.h"
#include "gp_Dir.h"
#include "BRepBuilderAPI_MakeEdge.h"
#include "BRepBuilderAPI_MakeShape.h"
#include "BRepBuilderAPI_Command.h"
#include "TopoDS_Vertex.h"
#include "TopoDS_Face.h"
#include "TopoDS_Edge.h"
#include "BRepFill.h"
#include "IGESControl_Controller.h"
#include "IGESControl_Writer.h"
#include "BRepLib_FindSurface.h"
#include "GeomAPI_IntSS.h"
#include "Geom_Surface.h"
#include "Geom_Curve.h"
#include "BRep_Tool.h"
#include "Standard_Transient.h"
#include "GeomLProp_SLProps.h"
#include "BRepTools.h"
#include "BRepOffset_Offset.h"